### ISSUE TITLE
Publish the library on jcenter

### ISSUE THREAD

**Issue by friedger** [sufficientlysecure/donations#19]
For example use https://github.com/novoda/bintray-release

**Comment by GuyMicciche** [comment]
Hello, is there anyway you can provide me with a .jar file of your library? Email is king.guy@outlook.com.

**Comment by druidamix** [comment]
I Agree, publish to jcenter or maven.

**Comment by Ph1b** [comment]
+1!

**Comment by dschuermann** [comment]
done
