### ISSUE TITLE
Add better Bitcoin support using Bitcoin Wallet API

### ISSUE THREAD

**Issue by dschuermann** [SufficientlySecure/donations#23]
See https://github.com/schildbach/bitcoin-wallet/wiki/InAppPayments

**Comment by friedger** [comment]
@dschuermann Could you clarify what this issue is about?
I only see possible two enhancements:
* Getting a result back
* Directing to bitcoin wallet download if not installed

**Comment by dschuermann** [comment]
@friedger Hmm, you are right, there is not much more to do here :P 
I think even the two points raised by you are not really needed, so I am closing this one.
