### ISSUE TITLE
Attempt to read from field 'java.lang.String org.sufficientlysecure.donations.google.util.Purchase.mItemType' on a null object reference

### ISSUE THREAD

**Issue by conzorz** [SufficientlySecure/donations#24]
Fatal Exception: java.lang.NullPointerException
Attempt to read from field 'java.lang.String org.sufficientlysecure.donations.google.util.Purchase.mItemType' on a null object reference
 raw
org.sufficientlysecure.donations.google.util.IabHelper.consume (IabHelper.java)
org.sufficientlysecure.donations.google.util.IabHelper$3.run (IabHelper.java)
java.lang.Thread.run (Thread.java:818)

**Comment by dschuermann** [comment]
When does this happen?
I need more information!

**Comment by dschuermann** [comment]
not enough information provided. closing
