### ISSUE TITLE
unmanaged vs managed in-app product

### ISSUE THREAD

**Issue by mxttie** [SufficientlySecure/donations#25]
Hi,

the readme of this library states that one should create unmanaged products in the developer console. However, i read that since billing v3 only managed products are available? Is this a bug in the readme or am i missing something?

thanks
matthias

**Comment by vipulpurohit** [comment]
I tried this library with a managed product but when I try to purchase item it says "The item you requested is not available for purchase"

**Comment by dschuermann** [comment]
@mxttie This should also work with managed products, but I haven't tested it. Please report back, what worked for you.

@vipulpurohit You can not purchase the products with the same Google account that you used to publish the 
app.

**Comment by mxttie** [comment]
@dschuermann i can confirm that it works with managed products
