### ISSUE TITLE
Genymotion emulator: NullPointerException on run

### ISSUE THREAD

**Issue by smrtnik** [SufficientlySecure/donations#26]
I could get it working changing:

public class IabHelper {
.....
List<ResolveInfo> tmpList = mContext.getPackageManager().queryIntentServices(serviceIntent, 0);
        if (tmpList==null && !tmpList.isEmpty()) {
....

In my case tmpList is null

Log file:
10-06 23:43:33.876 987-987/org.sufficientlysecure.donations.example D/dalvikvm: Late-enabling CheckJNI
10-06 23:43:33.988 987-987/org.sufficientlysecure.donations.example D/Donations Library: Creating IAB helper.
10-06 23:43:33.992 987-987/org.sufficientlysecure.donations.example D/Donations Library: Starting setup.
10-06 23:43:33.992 987-987/org.sufficientlysecure.donations.example D/IabHelper: Starting in-app billing setup.
10-06 23:43:33.992 987-987/org.sufficientlysecure.donations.example D/AndroidRuntime: Shutting down VM
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa62ed288)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime: FATAL EXCEPTION: main
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.sufficientlysecure.donations.example/org.sufficientlysecure.donations.example.DonationsActivity}: java.lang.NullPointerException
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.app.ActivityThread.access$600(ActivityThread.java:130)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4745)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:  Caused by: java.lang.NullPointerException
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at org.sufficientlysecure.donations.google.util.IabHelper.startSetup(IabHelper.java:268)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at org.sufficientlysecure.donations.DonationsFragment.onActivityCreated(DonationsFragment.java:242)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1797)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:979)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1163)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.app.Activity.performStart(Activity.java:5018)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2032)
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.app.ActivityThread.access$600(ActivityThread.java:130) 
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99) 
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137) 
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4745) 
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511) 
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
10-06 23:43:33.996 987-987/org.sufficientlysecure.donations.example E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

**Comment by dschuermann** [comment]
fixed with https://github.com/SufficientlySecure/donations/pull/27
